// Configuration data

export const translations = {
  en: {
    subtitle: "What To Play Today",
    "time-question": "How much time you have to play?",
    "time-30min": "30 min",
    "time-1-2hrs": "1-2 hours",
    "time-long": "A long while",
    "mood-question": "Mood?",
    "mood-chill": "Chill",
    "mood-sweat": "Sweat",
    "mood-think": "Think",
    "mode-question": "Single?",
    "mode-solo": "Solo",
    "mode-friends": "With Friends",
    "find-games": "Find games",
    reset: "Reset",
    "your-game": "Your game:",
    "dont-care": "Don't care",
    "server-error": "Failed to connect to server. Please try again.",
    "error-title": "Error",
    "check-requirements": "Check Requirements",
    "steam-placeholder": "Enter Steam nickname...",
    "fetch-library": "Fetch Library",
    "select-game": "Select a game to check",
  },
  ru: {
    subtitle: "Во что поиграть сегодня",
    "time-question": "Сколько у тебя времени?",
    "time-30min": "30 мин",
    "time-1-2hrs": "1-2 часа",
    "time-long": "Долго",
    "mood-question": "Вайб?",
    "mood-chill": "Чилл",
    "mood-sweat": "Потеть",
    "mood-think": "Думать",
    "mode-question": "Режим?",
    "mode-solo": "Соло",
    "mode-friends": "С друзьями",
    "find-games": "Найти игры",
    reset: "Сброс",
    "your-game": "Твоя игра:",
    "dont-care": "Мне всё равно",
    "server-error": "Не удалось подключиться к серверу. Попробуйте снова.",
    "error-title": "Ошибка",
    "check-requirements": "Проверить требования",
    "steam-placeholder": "Введите никнейм Steam...",
    "fetch-library": "Загрузить библиотеку",
    "select-game": "Выбери игру для проверки",
  },
  uk: {
    subtitle: "У Що Пограти Сьогодні",
    "time-question": "Скільки часу є?",
    "time-30min": "30 хв",
    "time-1-2hrs": "1-2 години",
    "time-long": "Довго",
    "mood-question": "Настрій?",
    "mood-chill": "Чілл",
    "mood-sweat": "Потіти",
    "mood-think": "Думати",
    "mode-question": "Режим?",
    "mode-solo": "Соло",
    "mode-friends": "З друзями",
    "find-games": "Знайти ігри",
    reset: "Скинути",
    "your-game": "Твоя гра:",
    "dont-care": "Мені все одно",
    "server-error": "Не вдалося підключитися до серверу. Спробуйте ще раз.",
    "error-title": "Помилка",
    "check-requirements": "Перевірити вимоги",
    "steam-placeholder": "Введіть нікнейм Steam...",
    "fetch-library": "Завантажити бібліотеку",
    "select-game": "Вибери гру для перевірки",
  },
};

export const moodToVibe = {
  Chill: "chill",
  Sweat: "sweat",
  Think: "brain",
};
