export const translations = {
  en: {
    subtitle: "What To Play Today",
    "time-question": "How much time you have to play?",
    "time-30min": "30 min",
    "time-1-2hrs": "1-2 hours",
    "time-long": "A long while",
    "mood-question": "Mood?",
    "mood-chill": "Chill",
    "mood-sweat": "Sweat",
    "mood-think": "Think",
    "mode-question": "Single?",
    "mode-solo": "Solo",
    "mode-friends": "With Friends",
    "find-games": "Find games",
    loading: "Loading...",
    "fetching-library": "Fetching library, stand by...",
    reset: "Reset",
    "your-game": "Your game:",
    "dont-care": "Don't care",
    "server-error": "Failed to connect to server. Please try again.",
    "error-title": "Error",
    "check-requirements": "Check Requirements",
    "steam-placeholder": "Enter Steam nickname...",
    "fetch-library": "Fetch Library",
    "select-game": "Select a game to check",
    "select-all-filters": "Please select all filters (Mood, Time, and Mode) for best results",
    "clear-nickname": "Clear",
    "confirm-clear-nickname": "Are you sure you want to clear the Steam nickname?",
    "confirm-clear-nickname-with-library": "Are you sure you want to clear the Steam library? (No nickname in field)",
    "confirm-clear-nickname-with-nickname": "Are you sure you want to clear the Steam nickname? (No library stored)",
    "confirm-clear-nickname-both": "Are you sure you want to clear the Steam nickname and library?",
    "faq": "FAQ",
    "faq-title": "FAQ",
    "faq-demo-title": "Work in Progress",
    "faq-demo-text": "This is a demo version. Some features may not work as expected.",
    "faq-steam-title": "How to load your Steam library",
    "faq-steam-text": "You can load your Steam library by entering your Steam ID or vanity URL in the field below.",
    "faq-steam-warning": "Important: Your Steam profile must be public and your game activity visible, otherwise Steam API will restrict access to your games list.",
    "faq-steps-title": "How to find your Steam ID / Vanity URL:",
    "faq-step-1": "Go to your Steam profile",
    "faq-step-2": "Look at the URL - it will show either a custom name (vanity URL) or a 17-digit number (Steam ID)",
    "faq-step-3": "Copy and paste it into the input field",
    "faq-step-4": "Click the checkmark button to fetch your library",
  },
  ru: {
    subtitle: "Во что поиграть сегодня",
    "time-question": "Сколько у тебя времени?",
    "time-30min": "30 мин",
    "time-1-2hrs": "1-2 часа",
    "time-long": "Долго",
    "mood-question": "Вайб?",
    "mood-chill": "Чилл",
    "mood-sweat": "Потеть",
    "mood-think": "Думать",
    "mode-question": "Режим?",
    "mode-solo": "Соло",
    "mode-friends": "С друзьями",
    "find-games": "Найти игры",
    loading: "Загрузка...",
    "fetching-library": "Загрузка библиотеки, подождите...",
    "dont-care": "Мне всё равно",
    "server-error": "Не удалось подключиться к серверу. Попробуйте снова.",
    "error-title": "Ошибка",
    "check-requirements": "Проверить требования",
    "steam-placeholder": "Введите никнейм Steam...",
    "fetch-library": "Загрузить библиотеку",
    "select-game": "Выбери игру для проверки",
    "select-all-filters": "Пожалуйста, выберите все фильтры (Вайб, Время и Режим) для лучших результатов",
    "clear-nickname": "Очистить",
    "confirm-clear-nickname": "Вы уверены, что хотите очистить никнейм Steam?",
    "confirm-clear-nickname-with-library": "Вы уверены, что хотите очистить библиотеку Steam? (Никнейм не введён)",
    "confirm-clear-nickname-with-nickname": "Вы уверены, что хотите очистить никнейм Steam? (Библиотека не сохранена)",
    "confirm-clear-nickname-both": "Вы уверены, что хотите очистить никнейм и библиотеку Steam?",
    "faq": "FAQ",
    "faq-title": "FAQ",
    "faq-demo-title": "В разработке",
    "faq-demo-text": "Это демо-версия. Некоторые функции могут работать не так, как ожидается.",
    "faq-steam-title": "Как загрузить свою библиотеку Steam",
    "faq-steam-text": "Вы можете загрузить свою библиотеку Steam, введя Steam ID или vanity URL в поле ниже.",
    "faq-steam-warning": "Важно: Ваш профиль Steam должен быть открытым, а информация об игровой активности видимой, иначе Steam API ограничит доступ к списку игр.",
    "faq-steps-title": "Как найти Steam ID / Vanity URL:",
    "faq-step-1": "Перейдите в свой профиль Steam",
    "faq-step-2": "Посмотрите на URL - там будет либо кастомное имя (vanity URL), либо 17-значное число (Steam ID)",
    "faq-step-3": "Скопируйте и вставьте в поле ввода",
    "faq-step-4": "Нажмите кнопку с галочкой для загрузки библиотеки",
  },
  uk: {
    subtitle: "У Що Пограти Сьогодні",
    "time-question": "Скільки часу є?",
    "time-30min": "30 хв",
    "time-1-2hrs": "1-2 години",
    "time-long": "Довго",
    "mood-question": "Настрій?",
    "mood-chill": "Чілл",
    "mood-sweat": "Потіти",
    "mood-think": "Думати",
    "mode-question": "Режим?",
    "mode-solo": "Соло",
    "mode-friends": "З друзями",
    "find-games": "Знайти ігри",
    loading: "Завантаження...",
    "fetching-library": "Завантаження бібліотеки, зачекайте...",
    "dont-care": "Мені все одно",
    "server-error": "Не вдалося підключитися до серверу. Спробуйте ще раз.",
    "error-title": "Помилка",
    "check-requirements": "Перевірити вимоги",
    "steam-placeholder": "Введіть нікнейм Steam...",
    "fetch-library": "Завантажити бібліотеку",
    "select-game": "Вибери гру для перевірки",
    "select-all-filters": "Будь ласка, виберіть всі фільтри (Настрій, Час і Режим) для найкращих результатів",
    "clear-nickname": "Очистити",
    "confirm-clear-nickname": "Ви впевнені, що хочете очистити нікнейм Steam?",
    "confirm-clear-nickname-with-library": "Ви впевнені, що хочете очистити бібліотеку Steam? (Нікнейм не введено)",
    "confirm-clear-nickname-with-nickname": "Ви впевнені, що хочете очистити нікнейм Steam? (Бібліотека не збережена)",
    "confirm-clear-nickname-both": "Ви впевнені, що хочете очистити нікнейм і бібліотеку Steam?",
    "faq": "FAQ",
    "faq-title": "FAQ",
    "faq-demo-title": "В розробці",
    "faq-demo-text": "Це демо-версія. Деякі функції можуть працювати не так, як очікується.",
    "faq-steam-title": "Як завантажити свою бібліотеку Steam",
    "faq-steam-text": "Ви можете завантажити свою бібліотеку Steam, ввівши Steam ID або vanity URL у поле нижче.",
    "faq-steam-warning": "Важливо: Ваш профіль Steam має бути відкритим, а інформація про ігрову активність видимою, інакше Steam API обмежить доступ до списку ігор.",
    "faq-steps-title": "Як знайти Steam ID / Vanity URL:",
    "faq-step-1": "Перейдіть у свій профіль Steam",
    "faq-step-2": "Подивіться на URL - там буде або кастомне ім'я (vanity URL), або 17-значне число (Steam ID)",
    "faq-step-3": "Скопіюйте та вставте у поле вводу",
    "faq-step-4": "Натисніть кнопку з галочкою для завантаження бібліотеки",
  },
};

export const moodToVibe = {
  Chill: "chill",
  Sweat: "sweat",
  Think: "brain",
  Чилл: "chill",
  Потеть: "sweat",
  Думать: "brain",
  "Чілл": "chill",
  Потіти: "sweat",
  Думати: "brain",
};

// Map UI time values to backend filter values
export const timeToDuration = {
  "30 min": "short",
  "30min": "short",
  "30\nmin": "short",
  "30 \nmin": "short",
  "1-2 hours": "medium",
  "1-2hours": "medium",
  "A long while": "long",
  "30 мин": "short",
  "A long while": "long",
  " 30 мин": "short",
  "30мин": "short",
  "30 \nмин": "short",
  "1-2 часа": "medium",
  "1-2чахв": "short",
  "30 са": "medium",
  "Долго": "long",
  " 30 хв": "short",
  "30хв": "short",
  "30 \nхв": "short",
  "1-2 години": "medium",
  "1-2години": "medium",
  "Довго": "long",
};
